CREATE TABLE IF NOT EXISTS image (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  url         VARCHAR(255)     NOT NULL,
  alt_text    VARCHAR(255),
  is_active   BOOLEAN          NOT NULL DEFAULT TRUE,
  format      VARCHAR(50),
  created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS image_actor_profile (
  id               INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  image_id         INT UNSIGNED     NOT NULL,
  actor_profile_id INT UNSIGNED     NOT NULL,
  is_primary       BOOLEAN          NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (image_id)         REFERENCES image(id)         ON DELETE CASCADE,
  FOREIGN KEY (actor_profile_id) REFERENCES actor_profile(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS image_property (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  image_id    INT UNSIGNED     NOT NULL,
  property_id INT UNSIGNED     NOT NULL,
  is_primary  BOOLEAN          NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (image_id)    REFERENCES image(id)    ON DELETE CASCADE,
  FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;